//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Jdt {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Jdt.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string DefaultSourceFileName {
            get {
                return ResourceManager.GetString("DefaultSourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        internal static string DefaultTransformFileName {
            get {
                return ResourceManager.GetString("DefaultTransformFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid attribute for this transformation.
        /// </summary>
        internal static string ErrorMessage_InvalidAttribute {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transformation attributes.
        /// </summary>
        internal static string ErrorMessage_InvalidAttributes {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid transform value for Remove.
        /// </summary>
        internal static string ErrorMessage_InvalidRemoveValue {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidRemoveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid transform value for Rename.
        /// </summary>
        internal static string ErrorMessage_InvalidRenameValue {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidRenameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid JDT verb.
        /// </summary>
        internal static string ErrorMessage_InvalidVerb {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires both path and value.
        /// </summary>
        internal static string ErrorMessage_MergeAttributes {
            get {
                return ResourceManager.GetString("ErrorMessage_MergeAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path attribute must be a string.
        /// </summary>
        internal static string ErrorMessage_PathContents {
            get {
                return ResourceManager.GetString("ErrorMessage_PathContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove requires the path attribute.
        /// </summary>
        internal static string ErrorMessage_RemoveAttributes {
            get {
                return ResourceManager.GetString("ErrorMessage_RemoveAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove root.
        /// </summary>
        internal static string ErrorMessage_RemoveRoot {
            get {
                return ResourceManager.GetString("ErrorMessage_RemoveRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename requires both path and value attributes.
        /// </summary>
        internal static string ErrorMessage_RenameAttributes {
            get {
                return ResourceManager.GetString("ErrorMessage_RenameAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename node.
        /// </summary>
        internal static string ErrorMessage_RenameNode {
            get {
                return ResourceManager.GetString("ErrorMessage_RenameNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace requires both path and value attributes.
        /// </summary>
        internal static string ErrorMessage_ReplaceAttributes {
            get {
                return ResourceManager.GetString("ErrorMessage_ReplaceAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot replace root.
        /// </summary>
        internal static string ErrorMessage_ReplaceRoot {
            get {
                return ResourceManager.GetString("ErrorMessage_ReplaceRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value attribute must be a string.
        /// </summary>
        internal static string ErrorMessage_ValueContents {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node {0} was not found.
        /// </summary>
        internal static string WarningMessage_NodeNotFound {
            get {
                return ResourceManager.GetString("WarningMessage_NodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No nodes match the given path.
        /// </summary>
        internal static string WarningMessage_NoResults {
            get {
                return ResourceManager.GetString("WarningMessage_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove node.
        /// </summary>
        internal static string WarningMessage_UnableToRemove {
            get {
                return ResourceManager.GetString("WarningMessage_UnableToRemove", resourceCulture);
            }
        }
    }
}
