trigger:
  batch: true
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - .github
    - doc/
    - '*.md'
    - .vscode/
    - .github/
    - azure-pipelines/release.yml

    schedules:
      # Weekly api-scan builds
    - cron: "0 10 * * Sun" # Every Sunday @ 2 am PST
      displayName: Weekly api-scan
      always: true
      branches:
        include:
        - main

parameters:
- name: includeMacOS
  displayName: Build on macOS
  type: boolean
  default: false # macOS is often bogged down in Azure Pipelines
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true
- name: RunApiScanTools
  displayName: Run API Scan?
  type: boolean
  default: false

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  codecov_token: 4dc9e7e2-6b01-4932-a180-847b52b43d35 # Get a new one from https://codecov.io/
  ci_feed: https://pkgs.dev.azure.com/andrewarnott/_packaging/CI/nuget/v3/index.json # Azure Artifacts feed URL
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages/

jobs:
- template: azure-pipelines/build.yml
  parameters:
    includeMacOS: ${{ parameters.includeMacOS }}
    RunTests: ${{ parameters.RunTests }}
