<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>false</IsTestProject>
    <RuntimeIdentifier>$(DefaultRuntimeIdentifier)</RuntimeIdentifier>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <Import Project="..\AOT.props" />

  <ItemGroup>
    <AdditionalFiles Remove="..\..\stylecop.json" />
    <AdditionalFiles Include="..\..\src\stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.VisualStudio.Jdt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Microsoft.VisualStudio.Jdt\Microsoft.VisualStudio.Jdt.csproj" />
  </ItemGroup>
</Project>
